### ISSUE TITLE
[investigating] lswifi broken on Windows11 21H2

### ISSUE THREAD

**Issue by junimi** [joshschmelzle/lswifi#28]
Hi Josh, I installed lswifi as recommended and it breaks on execution. My setup:

Windows 11 21H2 build 22000.1219
Python 3.10.8
lswifi 0.1.29

PS C:\Users\myusername> lswifi
Traceback (most recent call last):
  File "C:\Users\myusername\AppData\Local\Programs\Python\Python310\lib\site-packages\lswifi\client.py", line 367, in __init__
    self.mac = iface.mac
AttributeError: 'WirelessInterface' object has no attribute 'mac'
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\myusername\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\myusername\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1378, in run
    self.function(*self.args, **self.kwargs)
  File "C:\Users\myusername\AppData\Local\Programs\Python\Python310\lib\site-packages\lswifi\client.py", line 106, in __internal_call
    self._function(*self._args, **self._kwargs)
  File "C:\Users\myusername\AppData\Local\Programs\Python\Python310\lib\site-packages\lswifi\client.py", line 515, in scan_timeout
    f"timeout interval ({self.timeout_interval} seconds) for {self.mac} exceeded..."
AttributeError: 'Client' object has no attribute 'mac'

Would appreciate any idea,
Jan

**Comment by joshschmelzle** [comment]
Hi Jan,

Can you please run `getmac.exe` from a Windows terminal (cmd or powershell) and tell me the results?

**Comment by joshschmelzle** [comment]
#29 attempts to address problems this issue where the interface to mac address mapping fails.

@junimi please install and test https://pypi.org/project/lswifi/0.1.30/
