### ISSUE TITLE
Error: no wireless interfaces found

### ISSUE THREAD

**Issue by OlegXio** [joshschmelzle/lswifi#62]
`lswifi` command output:
```
C:\Users\1>lswifi
Exception in thread Thread-1 (WirelessInterfaceThread):
Traceback (most recent call last):
  File "D:\Program Files\Python-fornuitka\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "D:\Program Files\Python-fornuitka\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Program Files\Python-fornuitka\Lib\site-packages\lswifi\wlanapi.py", line 1647, in WirelessInterfaceThread
    ifaces[index] = WirelessInterface(info)
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python-fornuitka\Lib\site-packages\lswifi\wlanapi.py", line 927, in __init__
    self.map_guid_to_mac_and_connection_name(self.guid, self.description)
  File "D:\Program Files\Python-fornuitka\Lib\site-packages\lswifi\wlanapi.py", line 988, in map_guid_to_mac_and_connection_name
    if guid.lower() in iface.guid.lower():
                       ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'lower'
2024-12-20 21:45:49,206 [ERROR] lswifi.app: no wireless interfaces found
```

I am using a wired Ethernet connection, however usb wifi modem is connected:

```
C:\Users\1>netsh wlan show networks
Имя интерфейса: Беспроводная сеть
Сейчас видно следующее количество сетей: 4.

SSID 1:
    Тип сети:                 Инфраструктура
    Проверка подлинности:     Открыть
    Шифрование:               Нет

SSID 2: GlamurnayaZaraza_EXT
    Тип сети:                 Инфраструктура
    Проверка подлинности:     WPA2-Personal
    Шифрование:               CCMP

SSID 3: GlamurnayaZaraza
    Тип сети:                 Инфраструктура
    Проверка подлинности:     WPA2-Personal
    Шифрование:               CCMP

SSID 4: MOL_7XPLFN
    Тип сети:                 Инфраструктура
    Проверка подлинности:     WPA2-Personal
    Шифрование:               CCMP
```

**Comment by joshschmelzle** [comment]
Can you verify you're running the latest version?

**Comment by OlegXio** [comment]
> Can you verify you're running the latest version? lswifi --version should say 0.1.45.

```
C:\Users\1>lswifi -v
lswifi 0.1.45
```
p.s. I installed lswifi the same day I created the issue (21 dec)

**Comment by joshschmelzle** [comment]
I'm scraping the output of `netsh wlan show interfaces` to build a mapping of guid to mac address. Looks like it's failing. Perhaps poor handling of i18n on my side. Any chance you could share the output?

**Comment by joshschmelzle** [comment]
I've been able to reproduce this by changing the "Administrative Language Settings" and rebooting on Windows 10. Looking into how to handle this better. I will minimally add better error handling so that we can still get scan results even if the app fails to map the GUID.

```bash
C:\Users\jsz>netsh wlan show interfaces

В системе 1 интерфейс:

    Имя:                                Wi-Fi 6
    Описание:                       RZ608 Wi-Fi 6E 80MHz
    Идентификатор GUID:   d536cf7e-92a1-46be-b038-xxxxxxxxxxxx
    Физический адрес:       a8:93:4a:xx:xx:xx
    Состояние:                     Подключено
    SSID: Patron Saint Of Hotdogs
    BSSID: d0:4d:c6:xx:xx:xx
    Тип сети:                          Инфраструктура
    Тип радио:                        802.11ax
    Проверка подлинности:  WPA2-Personal
    Шифр:                                CCMP
    Режим подключения:      Автоматическое подключение
    Канал:                               44
    Скорость приема (Мбит/с):    573.5
    Скорость передачи (Мбит/с): 573.5
    Сигнал:                                     90%
    Профиль                : Patron Saint Of Hotdogs

    Состояние размещенной сети: Недоступно


C:\Users\jsz>lswifi
Exception in thread Thread-1 (WirelessInterfaceThread):
Traceback (most recent call last):
  File "C:\Users\jsz\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\jsz\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\jsz\AppData\Local\Programs\Python\Python311\Lib\site-packages\lswifi\wlanapi.py", line 1647, in WirelessInterfaceThread
    ifaces[index] = WirelessInterface(info)
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jsz\AppData\Local\Programs\Python\Python311\Lib\site-packages\lswifi\wlanapi.py", line 927, in __init__
    self.map_guid_to_mac_and_connection_name(self.guid, self.description)
  File "C:\Users\jsz\AppData\Local\Programs\Python\Python311\Lib\site-packages\lswifi\wlanapi.py", line 988, in map_guid_to_mac_and_connection_name
    if guid.lower() in iface.guid.lower():
                       ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'lower'
2024-12-31 20:07:01,936 [ERROR] lswifi.app: no wireless interfaces found
```

**Comment by joshschmelzle** [comment]
Bug fixed in 9481756. Will be in the next release.

**Comment by joshschmelzle** [comment]
This is fixed in v0.1.46. Please upgrade with `python -m pip install -U lswifi`.
