### ISSUE TITLE
ValueError when run from macOS 11.4 VM

### ISSUE THREAD

**Issue by joshschmelzle** [joshschmelzle/lswifi#7]
Using a Win10 developer VM (https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/) on macOS Big Sur produces `ValueError: 1062 is not a valid SystemErrorCodes`: 

```
C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Scripts>lswifi.exe --debug
2021-06-11 19:50:02,456 [DEBUG] lswifi.appsetup: args Namespace(iface=None, ies=None, sensitivity=None, g=False, a=False, six=False, include=None, exclude=None, bssid=None, apnames=False, uptime=False, width=None, ethers=False, append=None, display_ethers=False, data_location=False, get_current_ap=False, get_current_channel=False, raw=False, get_interface_info=False, list_interfaces=False, supported=False, json=False, export=None, bytefile=None, bytes=None, event_watcher=False, debug=10)
2021-06-11 19:50:02,456 [DEBUG] lswifi.appsetup: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]
2021-06-11 19:50:02,471 [DEBUG] asyncio: Using proactor: IocpProactor
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Scripts\lswifi.exe\__main__.py", line 7, in <module>
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\lswifi\__main__.py", line 67, in main
    loop.run_until_complete(main_task)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\lswifi\core.py", line 68, in scan
    interfaces = WLAN_API.WLAN.get_wireless_interfaces()
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\lswifi\wlanapi.py", line 1527, in get_wireless_interfaces
    handle = WLAN.open_handle()
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\lswifi\wlanapi.py", line 1399, in open_handle
    f"wlanapi.wlan.open_handle() failed: {SystemErrorCodes(result)}:{result}"
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\enum.py", line 360, in __call__
    return cls.__new__(cls, value)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\enum.py", line 678, in __new__
    raise ve_exc
ValueError: 1062 is not a valid SystemErrorCodes
```

**Comment by joshschmelzle** [comment]
I can't reproduce this. It seems to work fine. I am on macOS 11.6 now though. Closing.
